jobs:

- job: 'Test'
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python38:
        python.version: '3.8'
      Python39:
        python.version: '3.9'
      Python310:
        python.version: '3.10'
      Python311:
        python.version: '3.11'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      curl -sSL https://install.python-poetry.org | python3 -
      poetry install
    displayName: 'Install Poetry'

  - script: |
      poetry run black -l 100 --check dotstrings/*.py
    displayName: 'Format Check (Black)'

  - script: |
      poetry run pylint --rcfile=pylintrc dotstrings
      poetry run pylint --rcfile=pylintrc tests
    displayName: 'Lint'

  - script: |
      poetry run mypy --ignore-missing-imports dotstrings/
      poetry run mypy --ignore-missing-imports tests/
    displayName: 'Type Check'

  - script: |
      poetry run pytest tests --cov=dotstrings --cov-report xml --doctest-modules --junitxml=junit/test-results.xml
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

  # Publish Code Coverage Results
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage.xml
